#ifndef HSXQTUTILITIESGIS_GLOBAL_H
#define HSXQTUTILITIESGIS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HSXQTUTILITIESGIS_LIBRARY)
#define HSXQTUTILITIESGIS_EXPORT Q_DECL_EXPORT
#else
#define HSXQTUTILITIESGIS_EXPORT Q_DECL_IMPORT
#endif

#endif // HSXQTUTILITIESGIS_GLOBAL_H
