#ifndef QTUTILITIES_GLOBAL_H
#define QTUTILITIES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTUTILITIES_LIBRARY)
#  define QTUTILITIESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTUTILITIESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTUTILITIES_GLOBAL_H
