#ifndef HSXQTUTILITIESGIT_GLOBAL_H
#define HSXQTUTILITIESGIT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HSXQTUTILITIESGIT_LIBRARY)
#define HSXQTUTILITIESGIT_EXPORT Q_DECL_EXPORT
#else
#define HSXQTUTILITIESGIT_EXPORT Q_DECL_IMPORT
#endif

#endif // HSXQTUTILITIESGIT_GLOBAL_H
