#ifndef HSXQTUTILITIESCORE_GLOBAL_H
#define HSXQTUTILITIESCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HSXQTUTILITIESCORE_LIBRARY)
#define HSXQTUTILITIESCORE_EXPORT Q_DECL_EXPORT
#else
#define HSXQTUTILITIESCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // HSXQTUTILITIESCORE_GLOBAL_H
